# FOOD WEBS WITH HIGHER NODE FEATURE COVERAGE ONLY
## Using sub-graph of left-out food web as test case input
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/0_pca_components/hpo_best_configs.json --out_dir results/high_feature_coverage/0_pca_components-subgraph
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/5_pca_components/hpo_best_configs.json --out_dir results/high_feature_coverage/5_pca_components-subgraph
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/10_pca_components/hpo_best_configs.json --out_dir results/high_feature_coverage/10_pca_components-subgraph
## Using binary mask of full left-out food web as test case input
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/0_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/high_feature_coverage/0_pca_components-binary_adj
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/5_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/high_feature_coverage/5_pca_components-binary_adj
python src/train_final_models.py --webs_path final_datasets/high_feature_coverage-food_webs/ --species_path final_datasets/high_feature_coverage-node_features/ --best_params results/optimisation_results/high_feature_coverage/10_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/high_feature_coverage/10_pca_components-binary_adj


# # ALL WEIGHTED FOOD WEBS INCLUDING POOR NODE FEATURE COVERAGE
# ## Using sub-graph of left-out food web as test case input
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/0_pca_components/hpo_best_configs.json --out_dir results/all_weighted_networks/0_pca_components-subgraph
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/5_pca_components/hpo_best_configs.json --out_dir results/all_weighted_networks/5_pca_components-subgraph
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/10_pca_components/hpo_best_configs.json --out_dir results/all_weighted_networks/10_pca_components-subgraph
# ## Using binary mask of full left-out food web as test case input
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/0_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/all_weighted_networks/0_pca_components-binary_adj
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/5_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/all_weighted_networks/5_pca_components-binary_adj
python src/train_final_models.py --webs_path final_datasets/all_weighted_networks-food_webs/ --species_path final_datasets/all_weighted_networks-node_features/ --best_params results/optimisation_results/all_weighted_networks/10_pca_components/hpo_best_configs.json --use_bin_adj --out_dir results/all_weighted_networks/10_pca_components-binary_adj

